### ISSUE TITLE
这里的title名错误

### ISSUE THREAD

**Issue by LEBRON432** [huaweimin/zhihuDaily#8]
<body>
    <div class="background">
        <div class="transbox">
            <p>这是一段文本</p>
        </div>
    </div>

    <div>这是个不透明度为0.3的图片</div>
    <img src="images/xuehua.png" alt="xuehua" class="img"><br>
    <div>这是个不透明度为0.8的图片</div>
    <img src="images/erji.png" alt="erji" class="imgone"><br>

    <div class="select">赶紧选我好吗，等不及了</div><br>

    

    
    <div class="mix">注重保存与分享用户出游记忆资产，我们尊重并鼓励用户创作原创轻记</div>

    

    
</body>

**Comment by huaweimin** [comment]
6

**Comment by huaweimin** [comment]
> 这是一段文本
> 
> ```
> <div>这是个不透明度为0.3的图片</div>
> <img src="images/xuehua.png" alt="xuehua" class="img"><br>
> <div>这是个不透明度为0.8的图片</div>
> <img src="images/erji.png" alt="erji" class="imgone"><br>
> 
> <div class="select">赶紧选我好吗，等不及了</div><br>
> 
> 
> 
> 
> <div class="mix">注重保存与分享用户出游记忆资产，我们尊重并鼓励用户创作原创轻记</div>
> 
> 
> 
> 
> ```

6
